#!/bin/bash

### copy this file to your $HOME directory and modify acoording to your setup ###

# general environment vaiables
export METHOME="/home/pi/fidelio-capture-bit" # location of the code (i.e. the git clone directory)
export METVID="/home/pi/videos" # location where videos are going to be saved
export METDEV="/dev/video0" # video device of camera module

export CAMID='0' # camera id (single char: '0'-'9', 'a'-'z' or 'A'-'Z')

# camera longitude/latitude (decimal number)
export CAMLONG="49.869802"
export CAMLAT="8.778283"
